#!/bin/bash
tmp=$(tempfile)
sorted=$(tempfile)
for i in subs/*
do
	echo $(basename $i) $(awk '{print $NF}' $i) >> $tmp
done
sort -k2 $tmp > $sorted
sort -u -k2 $sorted > $tmp
diff -u $tmp $sorted
rm -f $tmp $sorted
