#!/bin/bash
# Designed to send off your blogs that no one can be bothered to setup a RSS feeder with
# Pipe from mutt

domain="sg.hackandtell.org"

tmp=$(tempfile)
cat > $tmp
subject="$(grep -m 1 '^Subject: ' $tmp | sed 's/^Subject: *//')"
esubject="$(php -r "echo rawurlencode('$subject');")"

for i in subs/*
do
	echo $(basename $i) $(cat $i)
done | grep hendry $list | # replace hendry with . when you want to send it off
while read id IP email
do
	{ sed '1,/^$/d' $tmp | markdown
	echo "<hr>"
	echo "<footer>"
	cat reminder.html
	echo "<p>Unsubscribe: <a href=http://$domain/unsubscribe/$id/$esubject>http://$domain/unsubscribe/$id/$subject</a></p>"
	echo "</footer>"
	} |
	mutt -e "set content_type=text/html" -e "my_hdr List-Unsubscribe: <http://$domain/unsub/$id/$esubject>" -s "$subject" $email
	if test "$?" -eq 0
	then
		echo OK $email
	else
		echo ERROR $email http://$domain/unsub/$id/failed-to-send
	fi
done

rm -f $tmp
